import xlrd
import xlwt
from xlutils.copy import copy
import os.path


def exportReportExcel(hisse,file,bilancoDonemi,ExcelRowClass):

    def createTopRow():
        bookSheetWrite.write(0, 0, "Hisse Adı")
        bookSheetWrite.write(0, 1, "Bilanço Dönemi Hasılat")
        bookSheetWrite.write(0, 2, "Önceki Yıl Aynı Çeyrek Hasılat")
        bookSheetWrite.write(0, 3, "Bilanço Dönemi Hasılat Değişimi")
        bookSheetWrite.write(0, 4, "Bir Önceki Bilanço Dönemi Hasılat")
        bookSheetWrite.write(0, 5, "Beş Önceki Bilanço Dönemi Hasılat")
        bookSheetWrite.write(0, 6, "Bir Önceki Bilanço Dönemi Hasılat Değişimi")
        bookSheetWrite.write(0, 7, "Bilanço Dönemi Hasılat Gelir Artışı Geçme Durumu")
        bookSheetWrite.write(0, 8, "Önceki Bilanço Dönemi Hasılat Gelir Artışı Geçme Durumu")
        bookSheetWrite.write(0, 9, "Bilanço Dönemi Faaliyet Karı")
        bookSheetWrite.write(0, 10, "Önceki Yıl Aynı Çeyrek Faaliyet Karı")
        bookSheetWrite.write(0, 11, "Bilanço Dönemi Faaliyet Karı Değişimi")
        bookSheetWrite.write(0, 12, "Bir Önceki Bilanço Dönemi Faaliyet Karı")
        bookSheetWrite.write(0, 13, "Beş Önceki Bilanço Dönemi Faaliyet Karı")
        bookSheetWrite.write(0, 14, "Önceki Bilanço Dönemi Faaliyet Kari Değişimi")
        bookSheetWrite.write(0, 15, "Bilanço Dönemi Faaliyet Karı Artışı Geçme Durumu")
        bookSheetWrite.write(0, 16, "Önceki Bilanço Dönemi Faaliyet Karı Artışı Geçme Durumu")
        bookSheetWrite.write(0, 17, "Bilanço Dönemi Ortalama Dolar Kuru")
        bookSheetWrite.write(0, 18, "Bilanço Dönemi Dolar Hasılat")
        bookSheetWrite.write(0, 19, "Önceki Yıl Aynı Çeyrek Dolar Hasılat")
        bookSheetWrite.write(0, 20, "Bilanço Dönemi Dolar Hasılat Değişimi")
        bookSheetWrite.write(0, 21, "Bir Önceki Bilanço Dönemi Dolar Hasılat Değişimi")
        bookSheetWrite.write(0, 22, "Bilanço Dönemi Dolar Hasılat Gelir Artışı Geçme Durumu")
        bookSheetWrite.write(0, 23, "Önceki Bilanço Dönemi Dolar Hasılat Gelir Artışı Geçme Durumu")
        bookSheetWrite.write(0, 24, "Bilanço Dönemi Dolar Faaliyet Kari")
        bookSheetWrite.write(0, 25, "Önceki Yıl Aynı Çeyrek Dolar Faaliyet Karı")
        bookSheetWrite.write(0, 26, "Bilanço Dönemi Dolar Faaliyet Karı Değişimi")
        bookSheetWrite.write(0, 27, "Önceki Bilanço Dönemi Dolar Faaliyet Karı Değişimi")
        bookSheetWrite.write(0, 28, "Bilanço Dönemi Dolar Faaliyet Kari Artışı Geçme Durumu")
        bookSheetWrite.write(0, 29, "Önceki Bilanço Dönemi Dolar Faaliyet Kari Artışı Geçme Durumu")
        bookSheetWrite.write(0, 30, "Sermaye")
        bookSheetWrite.write(0, 31, "Ana Ortaklık Payı")
        bookSheetWrite.write(0, 32, "Son 4 Bilanço Dönemi Hasılat Toplamı")
        bookSheetWrite.write(0, 33, "Önümüzdeki 4 Bilanço Dönemi Hasılat Tahmini")
        bookSheetWrite.write(0, 34, "Önümüzdeki 4 Bilanço Dönemi Faaliyet Kar Marjı Tahmini")
        bookSheetWrite.write(0, 35, "Faaliyet Kar Tahmini 1")
        bookSheetWrite.write(0, 36, "Faaliyet Kar Tahmini 2")
        bookSheetWrite.write(0, 37, "Ortalama Faaliyet Kar Tahmini")
        bookSheetWrite.write(0, 38, "Hisse Başına Kar Tahmini")
        bookSheetWrite.write(0, 39, "Bilanço Etkisi")
        bookSheetWrite.write(0, 40, "Bilanço Tarihi Hisse Fiyatı")
        bookSheetWrite.write(0, 41, "Gerçek Hisse Değeri")
        bookSheetWrite.write(0, 42, "Target Buy")
        bookSheetWrite.write(0, 43, "Gerçek Fiyata Uzaklık")
        bookSheetWrite.write(0, 44, "F/K Oranı")
        bookSheetWrite.write(0, 45, "HBK Oranı")
        bookSheetWrite.write(0, 46, "NetPro")
        bookSheetWrite.write(0, 47, "ForwardPE")

    def reportResults(rowNumber):

        bookSheetWrite.write(rowNumber, 0, hisse)
        bookSheetWrite.write(rowNumber, 1, ExcelRowClass.bilancoDonemiHasilat)
        bookSheetWrite.write(rowNumber, 2, ExcelRowClass.oncekiYilAyniCeyrekHasilat)
        bookSheetWrite.write(rowNumber, 3, ExcelRowClass.bilancoDonemiHasilatDegisimi)
        bookSheetWrite.write(rowNumber, 4, ExcelRowClass.birOncekiBilancoDonemiHasilat)
        bookSheetWrite.write(rowNumber, 5, ExcelRowClass.besOncekiBilancoDonemiHasilat)
        bookSheetWrite.write(rowNumber, 6, ExcelRowClass.birOncekiBilancoDonemiHasilatDegisimi)
        bookSheetWrite.write(rowNumber, 7, ExcelRowClass.bilancoDonemiHasilatDegisimiGecmeDurumu)
        bookSheetWrite.write(rowNumber, 8, ExcelRowClass.oncekiBilancoDonemiHasilatGelirArtisiGecmeDurumu)
        bookSheetWrite.write(rowNumber, 9, ExcelRowClass.bilancoDonemiFaaliyetKari)
        bookSheetWrite.write(rowNumber, 10, ExcelRowClass.oncekiYilAyniCeyrekFaaliyetKari)
        bookSheetWrite.write(rowNumber, 11, ExcelRowClass.bilancoDonemiFaaliyetKariDegisimi)
        bookSheetWrite.write(rowNumber, 12, ExcelRowClass.birOncekiBilancoDonemiFaaliyetKari)
        bookSheetWrite.write(rowNumber, 13, ExcelRowClass.besOncekiBilancoDonemiFaaliyetKari)
        bookSheetWrite.write(rowNumber, 14, ExcelRowClass.oncekiBilancoDonemiFaaliyetKariDegisimi)
        bookSheetWrite.write(rowNumber, 15, ExcelRowClass.bilancoDonemiFaaliyetKariArtisiGecmeDurumu)
        bookSheetWrite.write(rowNumber, 16, ExcelRowClass.oncekiBilancoDonemiFaaliyetKarArtisiGecmeDurumu)
        bookSheetWrite.write(rowNumber, 17, ExcelRowClass.bilancoDonemiOrtalamaDolarKuru)
        bookSheetWrite.write(rowNumber, 18, ExcelRowClass.bilancoDonemiDolarHasilat)
        bookSheetWrite.write(rowNumber, 19, ExcelRowClass.oncekiYilAyniCeyrekDolarHasilat)
        bookSheetWrite.write(rowNumber, 20, ExcelRowClass.bilancoDonemiDolarHasilatDegisimi)
        bookSheetWrite.write(rowNumber, 21, ExcelRowClass.birOncekiBilancoDonemiDolarHasilatDegisimi)
        bookSheetWrite.write(rowNumber, 22, ExcelRowClass.bilancoDonemiDolarHasilatGelirArtisiGecmeDurumu)
        bookSheetWrite.write(rowNumber, 23, ExcelRowClass.oncekiBilancoDonemiDolarHasilatGelirArtisiGecmeDurumu)
        bookSheetWrite.write(rowNumber, 24, ExcelRowClass.bilancoDonemiDolarFaaliyetKari)
        bookSheetWrite.write(rowNumber, 25, ExcelRowClass.dortOncekiBilancoDonemiDolarFaaliyetKari)
        bookSheetWrite.write(rowNumber, 26, ExcelRowClass.bilancoDonemiDolarFaaliyetKariDegisimi)
        bookSheetWrite.write(rowNumber, 27, ExcelRowClass.birOncekiBilancoDonemiDolarFaaliyetKariDegisimi)
        bookSheetWrite.write(rowNumber, 28, ExcelRowClass.bilancoDonemiDolarFaaliyetKariArtisiGecmeDurumu)
        bookSheetWrite.write(rowNumber, 29, ExcelRowClass.oncekiBilancoDonemiDolarFaaliyetKarArtisiGecmeDurumu)
        bookSheetWrite.write(rowNumber, 30, ExcelRowClass.sermaye)
        bookSheetWrite.write(rowNumber, 31, ExcelRowClass.anaOrtaklikPayi)
        bookSheetWrite.write(rowNumber, 32, ExcelRowClass.sonDortBilancoDonemiHasilatToplami)
        bookSheetWrite.write(rowNumber, 33, ExcelRowClass.onumuzdekiDortBilancoDonemiHasilatTahmini)
        bookSheetWrite.write(rowNumber, 34, ExcelRowClass.onumuzdekiDortBilancoDonemiFaaliyetKarMarjiTahmini)
        bookSheetWrite.write(rowNumber, 35, ExcelRowClass.faaliyetKariTahmini1)
        bookSheetWrite.write(rowNumber, 36, ExcelRowClass.faaliyetKariTahmini2)
        bookSheetWrite.write(rowNumber, 37, ExcelRowClass.ortalamaFaaliyetKariTahmini)
        bookSheetWrite.write(rowNumber, 38, ExcelRowClass.hisseBasinaOrtalamaKarTahmini)
        bookSheetWrite.write(rowNumber, 39, ExcelRowClass.bilancoEtkisi)
        bookSheetWrite.write(rowNumber, 40, ExcelRowClass.bilancoTarihiHisseFiyati)
        bookSheetWrite.write(rowNumber, 41, ExcelRowClass.gercekHisseDegeri)
        bookSheetWrite.write(rowNumber, 42, ExcelRowClass.targetBuy)
        bookSheetWrite.write(rowNumber, 43, ExcelRowClass.gercekFiyataUzaklik)
        bookSheetWrite.write(rowNumber, 44, ExcelRowClass.fkOrani)
        bookSheetWrite.write(rowNumber, 45, ExcelRowClass.hbkOrani)
        bookSheetWrite.write(rowNumber, 46, ExcelRowClass.netProKriteri)
        bookSheetWrite.write(rowNumber, 47, ExcelRowClass.forwardPeKriteri)

    if os.path.isfile(file):
        print("Rapor dosyası var, güncellenecek:", file)
        bookRead = xlrd.open_workbook(file, formatting_info=True)
        sheetRead = bookRead.sheet_by_index(0)
        rowNumber = sheetRead.nrows
        bookWrite = copy(bookRead)
        bookSheetWrite = bookWrite.get_sheet(0)
        reportResults(rowNumber)
        bookWrite.save(file)

    else:
        print("Rapor dosyası yeni oluşturulacak: ", file)
        bookWrite = xlwt.Workbook()
        bookSheetWrite = bookWrite.add_sheet(str(bilancoDonemi))
        createTopRow()
        reportResults(1)
        bookWrite.save(file)
